# Screen
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# Asteroids
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# Player
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

# Shooting
SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.2

# Scroing
SCORE_BASE = 100 
SCORE_LARGE_ASTEROID = SCORE_BASE * 1  # Example: 300 points
SCORE_MEDIUM_ASTEROID = SCORE_BASE * 2 # Example: 200 points
SCORE_SMALL_ASTEROID = SCORE_BASE * 3  # Example: 100 points

GAME_STATE_PLAYING = "playing"
GAME_STATE_OVER = "game_over"